# # Use an official Python runtime as a parent image
# FROM python:3.11-slim

# # Set the working directory in the container
# WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . /app

# # Create a virtual environment
# RUN python -m venv .venv

# # Install any needed packages specified in requirements.txt
# RUN .venv/bin/pip install --upgrade pip
# RUN .venv/bin/pip install -r requirements.txt

# # Make the Consumer.py script executable
# RUN chmod +x /app/Consumer/Consumer.py

# # Run the Consumer.py script
# CMD [".venv/bin/python", "/app/Consumer/Consumer.py"]
